/* AUTO-GENERATED by tools/build-button-catalog.js — do not edit by hand.
   Regenerate with:  node tools/build-button-catalog.js                  */
(function(){
  var BY_SCENE = {
  "tawaf-initial": [
    {
      "id": "",
      "text": "Let's Begin →",
      "cls": "ihram-btn-next",
      "onclick": "ihramNext()"
    },
    {
      "id": "",
      "text": "Skip",
      "cls": "ihram-btn-skip",
      "onclick": "ihramSkip()"
    },
    {
      "id": "",
      "text": "← Back",
      "cls": "ihram-btn-back",
      "onclick": "ihramBack()"
    },
    {
      "id": "",
      "text": "Continue →",
      "cls": "ihram-btn-next",
      "onclick": "ihramNext()"
    },
    {
      "id": "",
      "text": "Begin Your Tawaf 🕋",
      "cls": "ihram-btn-next",
      "onclick": "ihramStep2PlayVO();ihramSkip();"
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "",
      "text": "↺",
      "cls": "tcReset",
      "onclick": "tawafLapReset()"
    },
    {
      "id": "tcNextBtn",
      "text": "Next ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "",
      "text": "↺ Restart Tawaf",
      "cls": "tcReset",
      "onclick": "tawafLapReset();document.getElementById('tawafComplete').style.display='none';location.reload()"
    }
  ],
  "tawaf-ifadha": [
    {
      "id": "",
      "text": "Let's Begin →",
      "cls": "ihram-btn-next",
      "onclick": "ihramNext()"
    },
    {
      "id": "",
      "text": "Skip",
      "cls": "ihram-btn-skip",
      "onclick": "ihramSkip()"
    },
    {
      "id": "",
      "text": "← Back",
      "cls": "ihram-btn-back",
      "onclick": "ihramBack()"
    },
    {
      "id": "",
      "text": "Continue →",
      "cls": "ihram-btn-next",
      "onclick": "ihramNext()"
    },
    {
      "id": "",
      "text": "Begin Your Tawaf 🕋",
      "cls": "ihram-btn-next",
      "onclick": "ihramStep2PlayVO();ihramSkip();"
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "",
      "text": "↺",
      "cls": "tcReset",
      "onclick": "tawafLapReset()"
    },
    {
      "id": "tcNextBtn",
      "text": "Next ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "",
      "text": "↺ Restart Tawaf",
      "cls": "tcReset",
      "onclick": "tawafLapReset();document.getElementById('tawafComplete').style.display='none';location.reload()"
    }
  ],
  "tawaf-farewell": [
    {
      "id": "",
      "text": "Let's Begin →",
      "cls": "ihram-btn-next",
      "onclick": "ihramNext()"
    },
    {
      "id": "",
      "text": "Skip",
      "cls": "ihram-btn-skip",
      "onclick": "ihramSkip()"
    },
    {
      "id": "",
      "text": "← Back",
      "cls": "ihram-btn-back",
      "onclick": "ihramBack()"
    },
    {
      "id": "",
      "text": "Continue →",
      "cls": "ihram-btn-next",
      "onclick": "ihramNext()"
    },
    {
      "id": "",
      "text": "Begin Your Tawaf 🕋",
      "cls": "ihram-btn-next",
      "onclick": "ihramStep2PlayVO();ihramSkip();"
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "",
      "text": "↺",
      "cls": "tcReset",
      "onclick": "tawafLapReset()"
    },
    {
      "id": "tcNextBtn",
      "text": "Next ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "",
      "text": "↺ Restart Tawaf",
      "cls": "tcReset",
      "onclick": "tawafLapReset();document.getElementById('tawafComplete').style.display='none';location.reload()"
    }
  ],
  "safa-marwa": [
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "",
      "text": "&#x21BA;",
      "cls": "scReset",
      "onclick": "saiLapReset()"
    },
    {
      "id": "saiNextSceneBtn",
      "text": "Next Scene &#x25B8;",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "",
      "text": "&#x21BA; Restart Sa'i",
      "cls": "scReset",
      "onclick": "saiLapReset();document.getElementById('saiComplete').style.display='none';location.reload()"
    }
  ],
  "mina-8th": [
    {
      "id": "minaContinue",
      "text": "🕋 Continue to Jamarat ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "mnEndContinue",
      "text": "Continue to Next Scene \\u25b8",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "mnEndExplore",
      "text": "Keep Exploring",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "mnEndRestart",
      "text": "\\u21bb Restart Scene",
      "cls": "",
      "onclick": ""
    }
  ],
  "mina-tents-12": [
    {
      "id": "minaContinue",
      "text": "🕋 Continue to Jamarat ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "mnEndContinue",
      "text": "Continue to Next Scene \\u25b8",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "mnEndExplore",
      "text": "Keep Exploring",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "mnEndRestart",
      "text": "\\u21bb Restart Scene",
      "cls": "",
      "onclick": ""
    }
  ],
  "arafah-9th": [
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "arEndContinue",
      "text": "Continue to Muzdalifah \\u25b8",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "arEndExplore",
      "text": "Keep Exploring",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "arEndRestart",
      "text": "\\u21bb Restart Scene",
      "cls": "",
      "onclick": ""
    }
  ],
  "muzdalifah-9th": [
    {
      "id": "",
      "text": "Collect Again",
      "cls": "",
      "onclick": "resetPebbles()"
    },
    {
      "id": "",
      "text": "Begin Collecting ▸",
      "cls": "",
      "onclick": "dismissMuzGuide()"
    },
    {
      "id": "pbContinue",
      "text": "Continue to Next Scene ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "pbExplore",
      "text": "Keep Exploring",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "pbRestart",
      "text": "\\u21bb Restart Scene",
      "cls": "",
      "onclick": ""
    }
  ],
  "jamarat-10th": [
    {
      "id": "jamarThrowBtn",
      "text": "🪨 Throw Stone (1/7)",
      "cls": "",
      "onclick": "throwStone()"
    },
    {
      "id": "",
      "text": "Begin Stoning ▸",
      "cls": "",
      "onclick": "dismissGuide()"
    },
    {
      "id": "",
      "text": "Reset &amp; Repeat",
      "cls": "",
      "onclick": "resetJamarat()"
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    },
    {
      "id": "jamarToQurbani",
      "text": "Continue to Qurbani \\u25b8",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "jamarReset10",
      "text": "\\u21ba Restart",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "jamarChainBtn",
      "text": "Return to Mina (Tents) ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "jamarReplay",
      "text": "↺ Restart",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "jamarChainBtn",
      "text": "Stay for 13th Day Stoning ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "jamarChainBtn2",
      "text": "Leave for Farewell Tawaf ▸",
      "cls": "",
      "onclick": ""
    },
    {
      "id": "jamarChainBtn",
      "text": "Continue to Farewell Tawaf ▸",
      "cls": "",
      "onclick": ""
    }
  ],
  "jamarat-11th": [
    {
      "id": "jamarThrowBtn",
      "text": "?? Throw Stone (1/7)",
      "cls": "",
      "onclick": "throwStone()"
    },
    {
      "id": "",
      "text": "Begin Stoning &#x25B8;",
      "cls": "",
      "onclick": "dismissGuide()"
    },
    {
      "id": "",
      "text": "Reset &amp; Repeat",
      "cls": "",
      "onclick": "resetJamarat()"
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    }
  ],
  "jamarat-12th": [
    {
      "id": "jamarThrowBtn",
      "text": "?? Throw Stone (1/7)",
      "cls": "",
      "onclick": "throwStone()"
    },
    {
      "id": "",
      "text": "Begin Stoning &#x25B8;",
      "cls": "",
      "onclick": "dismissGuide()"
    },
    {
      "id": "",
      "text": "Reset &amp; Repeat",
      "cls": "",
      "onclick": "resetJamarat()"
    },
    {
      "id": "",
      "text": "'+btn+'",
      "cls": "",
      "onclick": "dismissBanner()"
    }
  ],
  "barber-umrah": [
    {
      "id": "umrahTrimContinue",
      "text": "🌙 Continue: Rest &amp; Prepare ▸",
      "cls": "",
      "onclick": ""
    }
  ],
  "qurbani-10th": [],
  "barber-hajj": [
    {
      "id": "barberContinue",
      "text": "🕋 Continue to Tawaf al-Ifadah",
      "cls": "",
      "onclick": ""
    }
  ],
  "rest-umrah": [
    {
      "id": "",
      "text": "Continue: Re-enter Ihram for Hajj ▸",
      "cls": "continue-btn",
      "onclick": "(function(){var inJ=new URL(window.location.href).searchParams.has('journey');if(inJ&&typeof window.jm!=='undefined'){window.jm.goToNext();}else{window.location.href='ihram-scene.html?context=re-enter';}})()"
    }
  ],
  "reenter-ihram": [
    {
      "id": "continueBtn",
      "text": "Continue ▸",
      "cls": "continue-btn",
      "onclick": ""
    }
  ]
};
  window.PPButtonCatalog = {
    forSceneKey: function(key){ return (BY_SCENE[key]||[]).slice(); }
  };
})();
