/* AUTO-GENERATED by tools/build-panorama-catalog.js — do not edit by hand.
   Regenerate with:  node tools/build-panorama-catalog.js                    */
(function(){
  var BY_FOLDER = {
  "1 Tawaf": [
    {
      "id": "panorama_8AF67A73_955C_4E01_41DA_44BCCE2B395A",
      "label": "3VID_20260214_185906_00_313_2026-03-09_14-17-23_screenshot"
    },
    {
      "id": "panorama_8CE4041C_9544_BA06_41E1_5E77B48B16C5",
      "label": "Entrance cleaned up 1"
    },
    {
      "id": "panorama_8AC63E8D_9544_C601_41E0_0A05A67E5557",
      "label": "Entrance cleaned up 2"
    },
    {
      "id": "panorama_7F92625E_71D8_25CE_41DA_487A76BA9DE1",
      "label": "main starting area"
    },
    {
      "id": "panorama_7F923456_71D8_2DDE_41B0_3A02DC4F7AF2",
      "label": "st maiin 2"
    },
    {
      "id": "panorama_7F9246DB_71D8_6AD6_41DA_A3880DC6DC13",
      "label": "st main 3"
    },
    {
      "id": "panorama_7F92DC96_71D8_1D5E_41BF_87B612A8A131",
      "label": "st main 4"
    },
    {
      "id": "panorama_79E55BA5_71D8_FB72_41B7_A25B94737386",
      "label": "st main 5"
    },
    {
      "id": "panorama_7F927F34_71D8_3B52_41C5_1D549449A4CF",
      "label": "st main 6"
    },
    {
      "id": "panorama_7F9209F0_71D8_66D3_41BA_B1BDEA583A8F",
      "label": "st1"
    },
    {
      "id": "panorama_89070D75_955C_4A01_41D4_F7F58617B959",
      "label": "Starting area"
    }
  ],
  "2 Safa and Marwa": [
    {
      "id": "panorama_740A042A_7348_ED6D_41CA_00F715E5C1F1",
      "label": "sm 1"
    },
    {
      "id": "panorama_740A4B20_7348_1B1D_414B_57A3ACAA5480",
      "label": "sm 10"
    },
    {
      "id": "panorama_740A723B_7348_2563_41CB_5A2CEC22E758",
      "label": "sm 12"
    },
    {
      "id": "panorama_740A504C_7348_2525_41D3_C8D1BB48BC81",
      "label": "sm 2"
    },
    {
      "id": "panorama_740A1B4A_7348_1B2D_41DA_9933A2BCF68E",
      "label": "sm 4"
    },
    {
      "id": "panorama_740AFE99_7348_3D2F_41DA_C332EB8AFB32",
      "label": "sm 5"
    },
    {
      "id": "panorama_740A3162_7348_271C_41C8_A19348304FB9",
      "label": "sm 6"
    },
    {
      "id": "panorama_740AD8F8_7348_66ED_41D2_7D271A004E6C",
      "label": "sm 8"
    },
    {
      "id": "panorama_740A0ECC_7348_3D25_41B0_C7A9B39DDDC5",
      "label": "sm11"
    },
    {
      "id": "panorama_740A4651_7349_ED3F_41B6_D405B45EE7A5",
      "label": "sm13"
    },
    {
      "id": "panorama_740A5998_7349_E72D_41B7_F54AA6C9078A",
      "label": "sm14"
    },
    {
      "id": "panorama_740BFCBB_7348_1D63_41D3_BE89C1C40E8B",
      "label": "sm15"
    },
    {
      "id": "panorama_740BF053_7348_253C_41D6_F878BC2CDC67",
      "label": "sm16"
    },
    {
      "id": "panorama_740A13FE_7348_2AE5_41D7_CAACA57ACA1E",
      "label": "sm17"
    },
    {
      "id": "panorama_740BF74C_7348_6B25_41B3_934B9A7E6149",
      "label": "sm18"
    },
    {
      "id": "panorama_740A39D2_7348_673D_41D5_D2B6068BAC98",
      "label": "sm19"
    },
    {
      "id": "panorama_74099DB6_7348_1F65_41D3_5CD744CD0EC7",
      "label": "sm20"
    },
    {
      "id": "panorama_77BBA118_7348_272D_41C8_26E405934981",
      "label": "sm21"
    },
    {
      "id": "panorama_740A17B1_7348_EB7F_41C1_DCBED82D9AE5",
      "label": "sm3"
    },
    {
      "id": "panorama_740AE547_7348_6F23_4193_A53471E108B1",
      "label": "sm7_"
    }
  ],
  "3 Mina": [
    {
      "id": "panorama_73D8B866_7C54_4D8A_41D3_BF331164945C",
      "label": "VID_20260217_110228_00_415_2026-03-26_13-49-17_screenshot"
    },
    {
      "id": "panorama_71926860_7348_651D_41CF_4F527C3458D3",
      "label": "VID_20260217_110228_00_415_2026-03-26_13-50-34_screenshot"
    },
    {
      "id": "panorama_71927B4B_7348_1B2C_41D5_37DB942B3C36",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-56-16_screenshot"
    },
    {
      "id": "panorama_6C853468_7C74_4586_41DA_AE4EE6CF6DBB",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-57-11_screenshot"
    },
    {
      "id": "panorama_71923E99_7348_3D2C_41C1_93341EEC3AA4",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-57-11_screenshot"
    },
    {
      "id": "panorama_71922218_7348_252D_4164_F2CCB12298D6",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-57-34_screenshot"
    },
    {
      "id": "panorama_71921588_7348_EF2C_41C8_763FA49B5275",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-58-10_screenshot"
    },
    {
      "id": "panorama_72AD4A6A_7C54_4D9A_41DC_AA69EFBD3C52",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-58-102_screenshot"
    },
    {
      "id": "panorama_719228EC_7348_E6E4_41B5_630DB1B2ED2A",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-58-45_screenshot"
    },
    {
      "id": "panorama_71923C76_7348_1DE4_41DA_E9934C960EDC",
      "label": "VID_20260217_110319_00_416_2026-03-26_13-59-23_screenshot"
    },
    {
      "id": "panorama_7192231A_7348_2B2C_41DA_55E72146579D",
      "label": "VID_20260217_110543_00_417_2026-03-26_14-03-22_screenshot"
    },
    {
      "id": "panorama_7192F61F_7348_6D24_41DA_EDBBE5AA7D75",
      "label": "VID_20260217_110710_00_418_2026-03-26_14-05-17_screenshot"
    },
    {
      "id": "panorama_719277C3_7348_6B23_41BE_FDB5D81BA3A9",
      "label": "VID_20260217_110710_00_418_2026-03-26_14-06-21_screenshot"
    },
    {
      "id": "panorama_71923E7F_7348_3DE4_41C2_F4334225E680",
      "label": "VID_20260217_111108_00_419_2026-03-26_14-07-08_screenshot"
    },
    {
      "id": "panorama_719CB208_7348_252C_41A4_857364637462",
      "label": "VID_20260217_112215_00_420_2026-03-26_14-07-35_screenshot"
    },
    {
      "id": "panorama_73DA460C_7349_ED24_41D8_12878DA30034",
      "label": "VID_20260217_112855_00_421_2026-03-26_14-09-48_screenshot"
    }
  ],
  "4 Arafah": [
    {
      "id": "panorama_84F849C6_8BDC_CA02_41D4_1DA97E53F8AC",
      "label": "IMG_20260217_140318_00_508_2026-03-26_15-13-18_screenshot"
    },
    {
      "id": "panorama_84B0CD28_8BC4_4A0E_4196_9526145973A3",
      "label": "VID_20260217_135711_00_501_2026-03-26_15-03-20_screenshot"
    },
    {
      "id": "panorama_84B0B216_8BC4_5E03_41C2_63DAE8F0223F",
      "label": "VID_20260217_135804_00_502_2026-03-26_15-04-02_screenshot"
    },
    {
      "id": "panorama_84B0C610_8BC4_461F_41D3_BFF9B8E12573",
      "label": "VID_20260217_135858_00_503_2026-03-26_15-04-26_screenshot"
    },
    {
      "id": "panorama_84B08A8A_8BDB_CE03_41D7_B3FBC1D014E9",
      "label": "VID_20260217_135858_00_503_2026-03-26_15-05-03_screenshot"
    },
    {
      "id": "panorama_84B05E99_8BDB_C601_41C9_AEF86400F8CD",
      "label": "VID_20260217_135858_00_503_2026-03-26_15-05-20_screenshot"
    },
    {
      "id": "panorama_84B0B29F_8BDB_FE01_41D0_DD7D22AA4C1E",
      "label": "VID_20260217_135858_00_503_2026-03-26_15-05-40_screenshot"
    },
    {
      "id": "panorama_84B046C6_8BDB_C602_41D3_B589D05EA4C1",
      "label": "VID_20260217_135858_00_503_2026-03-26_15-05-52_screenshot"
    },
    {
      "id": "panorama_84B08B46_8BDB_CE00_41D3_0D5976CC87BD",
      "label": "VID_20260217_140008_00_504_2026-03-26_15-06-20_screenshot"
    },
    {
      "id": "panorama_84B0801D_8BDB_BA01_41D3_E88B0BC5EF44",
      "label": "VID_20260217_140033_00_505_2026-03-26_15-08-03_screenshot"
    },
    {
      "id": "panorama_84B78498_8BDC_5A0E_41D6_50E011C85194",
      "label": "VID_20260217_140033_00_505_2026-03-26_15-08-14_screenshot"
    },
    {
      "id": "panorama_84B7C818_8BDC_4A0F_41A4_D10BC7B2C759",
      "label": "VID_20260217_140111_00_506_2026-03-26_15-08-36_screenshot"
    },
    {
      "id": "panorama_84B78C66_8BDC_4A03_41C6_469145D3BC03",
      "label": "VID_20260217_140111_00_506_2026-03-26_15-09-02_screenshot"
    },
    {
      "id": "panorama_84B7F067_8BDC_5A01_4193_04747C799AF6",
      "label": "VID_20260217_140111_00_506_2026-03-26_15-09-13_screenshot"
    },
    {
      "id": "panorama_84B7E4AE_8BDC_BA02_41D2_91B77753A9BB",
      "label": "VID_20260217_140111_00_506_2026-03-26_15-09-32_screenshot"
    },
    {
      "id": "panorama_84B7B906_8BDC_CA03_41DC_F2566DCE7782",
      "label": "VID_20260217_140155_00_507_2026-03-26_15-09-52_screenshot"
    },
    {
      "id": "panorama_84B79D4D_8BDC_CA01_4182_71A1FC5D9F5C",
      "label": "VID_20260217_140155_00_507_2026-03-26_15-12-08_screenshot"
    },
    {
      "id": "panorama_84B7A23D_8BDC_FE06_41D2_4E76BC077D21",
      "label": "VID_20260217_140155_00_507_2026-03-26_15-12-20_screenshot"
    },
    {
      "id": "panorama_84B7D642_8BDC_C602_41C1_2E46B09DA139",
      "label": "VID_20260217_140155_00_507_2026-03-26_15-12-40_screenshot"
    }
  ],
  "Jamarat Aqabah": [
    {
      "id": "panorama_691B217E_7C54_3E7A_41D3_35A255D72204",
      "label": "VID_20260217_115635_00_436_2026-03-26_14-35-01_screenshot"
    },
    {
      "id": "panorama_691B992A_7C54_CF9A_41A0_CFAD0184B4D8",
      "label": "VID_20260217_115715_00_437_2026-03-26_14-35-31_screenshot"
    },
    {
      "id": "panorama_691BD070_7C54_DD86_41D9_025F4E408EDC",
      "label": "VID_20260217_115715_00_437_2026-03-26_14-35-53_screenshot"
    },
    {
      "id": "panorama_691BD7D8_7C54_C286_41D8_87DAB3A1DC93",
      "label": "VID_20260217_115715_00_437_2026-03-26_14-36-07_screenshot"
    }
  ],
  "jamarat base": [
    {
      "id": "panorama_6F591A67_7C4B_CD8A_41C0_0DCF04356022",
      "label": "VID_20260217_113114_00_422_2026-03-26_14-11-21_screenshot"
    },
    {
      "id": "panorama_6F5941FB_7C4B_FE7A_41C1_EA414E1E2B9E",
      "label": "VID_20260217_113114_00_422_2026-03-26_14-11-50_screenshot"
    },
    {
      "id": "panorama_6F591952_7C4B_CF8A_41D7_689C35BD89CB",
      "label": "VID_20260217_113243_00_423_2026-03-26_14-12-12_screenshot"
    },
    {
      "id": "panorama_6F5970DD_7C4B_DEBE_41DB_10A09B73B61D",
      "label": "VID_20260217_113426_00_424_2026-03-26_14-13-12_screenshot"
    },
    {
      "id": "panorama_6F591866_7C4B_CD8D_41D2_AE17632D2077",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-13-49_screenshot"
    },
    {
      "id": "panorama_6F591FE4_7C4C_428E_41D7_A32CBCFD088E",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-14-15_screenshot"
    },
    {
      "id": "panorama_6F59071A_7C4C_43BA_41CA_786DF501A3F9",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-14-25_screenshot"
    },
    {
      "id": "panorama_6992C73E_7C4C_C3FA_41BD_59619C4CA785",
      "label": "VID_20260217_113702_00_426_2026-03-26_14-14-48_screenshot"
    },
    {
      "id": "panorama_6F5905C9_7C4C_4686_41AD_75765084A0FB",
      "label": "VID_20260217_113702_00_426_2026-03-26_14-15-15_screenshot"
    },
    {
      "id": "panorama_6F59FCD8_7C4C_4686_41B2_C265078ADAA7",
      "label": "VID_20260217_113823_00_427_2026-03-26_14-18-04_screenshot"
    },
    {
      "id": "panorama_6F5913E2_7C4C_428A_41C0_5AD96767B167",
      "label": "VID_20260217_113902_00_428_2026-03-26_14-18-53_screenshot"
    },
    {
      "id": "panorama_6F59CB18_7C4C_4386_41BB_D57C9370F526",
      "label": "VID_20260217_113932_00_429_2026-03-26_14-19-34_screenshot"
    },
    {
      "id": "panorama_6F59F27A_7C4C_427A_41D0_44DDEFCC0BC1",
      "label": "VID_20260217_113948_00_430_2026-03-26_14-20-18_screenshot"
    },
    {
      "id": "panorama_6F5A89E3_7C4C_CE8A_41D5_C47ED4591027",
      "label": "VID_20260217_114016_00_431_2026-03-26_14-20-59_screenshot"
    },
    {
      "id": "panorama_6F5960EC_7C4C_DE9D_41D1_E00E6F2F74FC",
      "label": "VID_20260217_114016_00_431_2026-03-26_14-21-13_screenshot"
    },
    {
      "id": "panorama_6F596864_7C4C_CD8E_41BB_4AD5C09CF432",
      "label": "VID_20260217_114224_00_432_2026-03-26_14-21-52_screenshot"
    },
    {
      "id": "panorama_6F594052_7C4C_FD8A_41DE_EBCF8977D568",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-24_screenshot"
    },
    {
      "id": "panorama_6F5AB7CA_7C4C_C29A_41D8_B732BD5E56B3",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-36_screenshot"
    },
    {
      "id": "panorama_6F595EB7_7C4C_C28A_4188_BA3415271B80",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-46_screenshot"
    },
    {
      "id": "panorama_6F5AA626_7C4C_C58A_41D3_2319D74A1D3A",
      "label": "VID_20260217_114443_00_434_2026-03-26_14-23-15_screenshot"
    },
    {
      "id": "panorama_6F5ACD8E_7C4C_469A_41D7_F15459ACDAD3",
      "label": "VID_20260217_114443_00_434_2026-03-26_14-23-39_screenshot"
    }
  ],
  "Jamarat Base 2": [
    {
      "id": "panorama_6F591A67_7C4B_CD8A_41C0_0DCF04356022",
      "label": "VID_20260217_113114_00_422_2026-03-26_14-11-21_screenshot"
    },
    {
      "id": "panorama_6F5941FB_7C4B_FE7A_41C1_EA414E1E2B9E",
      "label": "VID_20260217_113114_00_422_2026-03-26_14-11-50_screenshot"
    },
    {
      "id": "panorama_6F591952_7C4B_CF8A_41D7_689C35BD89CB",
      "label": "VID_20260217_113243_00_423_2026-03-26_14-12-12_screenshot"
    },
    {
      "id": "panorama_6F5970DD_7C4B_DEBE_41DB_10A09B73B61D",
      "label": "VID_20260217_113426_00_424_2026-03-26_14-13-12_screenshot"
    },
    {
      "id": "panorama_6F591866_7C4B_CD8D_41D2_AE17632D2077",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-13-49_screenshot"
    },
    {
      "id": "panorama_6F591FE4_7C4C_428E_41D7_A32CBCFD088E",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-14-15_screenshot"
    },
    {
      "id": "panorama_6F59071A_7C4C_43BA_41CA_786DF501A3F9",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-14-25_screenshot"
    },
    {
      "id": "panorama_6992C73E_7C4C_C3FA_41BD_59619C4CA785",
      "label": "VID_20260217_113702_00_426_2026-03-26_14-14-48_screenshot"
    },
    {
      "id": "panorama_6F5905C9_7C4C_4686_41AD_75765084A0FB",
      "label": "VID_20260217_113702_00_426_2026-03-26_14-15-15_screenshot"
    },
    {
      "id": "panorama_6F59FCD8_7C4C_4686_41B2_C265078ADAA7",
      "label": "VID_20260217_113823_00_427_2026-03-26_14-18-04_screenshot"
    },
    {
      "id": "panorama_6F5913E2_7C4C_428A_41C0_5AD96767B167",
      "label": "VID_20260217_113902_00_428_2026-03-26_14-18-53_screenshot"
    },
    {
      "id": "panorama_6F59CB18_7C4C_4386_41BB_D57C9370F526",
      "label": "VID_20260217_113932_00_429_2026-03-26_14-19-34_screenshot"
    },
    {
      "id": "panorama_6F59F27A_7C4C_427A_41D0_44DDEFCC0BC1",
      "label": "VID_20260217_113948_00_430_2026-03-26_14-20-18_screenshot"
    },
    {
      "id": "panorama_6F5A89E3_7C4C_CE8A_41D5_C47ED4591027",
      "label": "VID_20260217_114016_00_431_2026-03-26_14-20-59_screenshot"
    },
    {
      "id": "panorama_6F5960EC_7C4C_DE9D_41D1_E00E6F2F74FC",
      "label": "VID_20260217_114016_00_431_2026-03-26_14-21-13_screenshot"
    },
    {
      "id": "panorama_6F596864_7C4C_CD8E_41BB_4AD5C09CF432",
      "label": "VID_20260217_114224_00_432_2026-03-26_14-21-52_screenshot"
    },
    {
      "id": "panorama_6F594052_7C4C_FD8A_41DE_EBCF8977D568",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-24_screenshot"
    },
    {
      "id": "panorama_6F5AB7CA_7C4C_C29A_41D8_B732BD5E56B3",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-36_screenshot"
    },
    {
      "id": "panorama_6F595EB7_7C4C_C28A_4188_BA3415271B80",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-46_screenshot"
    },
    {
      "id": "panorama_6F5AA626_7C4C_C58A_41D3_2319D74A1D3A",
      "label": "VID_20260217_114443_00_434_2026-03-26_14-23-15_screenshot"
    },
    {
      "id": "panorama_6F5ACD8E_7C4C_469A_41D7_F15459ACDAD3",
      "label": "VID_20260217_114443_00_434_2026-03-26_14-23-39_screenshot"
    }
  ],
  "Jamarat rooftop basement": [
    {
      "id": "panorama_6F591A67_7C4B_CD8A_41C0_0DCF04356022",
      "label": "VID_20260217_113114_00_422_2026-03-26_14-11-21_screenshot"
    },
    {
      "id": "panorama_6F5941FB_7C4B_FE7A_41C1_EA414E1E2B9E",
      "label": "VID_20260217_113114_00_422_2026-03-26_14-11-50_screenshot"
    },
    {
      "id": "panorama_6F591952_7C4B_CF8A_41D7_689C35BD89CB",
      "label": "VID_20260217_113243_00_423_2026-03-26_14-12-12_screenshot"
    },
    {
      "id": "panorama_6F5970DD_7C4B_DEBE_41DB_10A09B73B61D",
      "label": "VID_20260217_113426_00_424_2026-03-26_14-13-12_screenshot"
    },
    {
      "id": "panorama_6F591866_7C4B_CD8D_41D2_AE17632D2077",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-13-49_screenshot"
    },
    {
      "id": "panorama_6F591FE4_7C4C_428E_41D7_A32CBCFD088E",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-14-15_screenshot"
    },
    {
      "id": "panorama_6F59071A_7C4C_43BA_41CA_786DF501A3F9",
      "label": "VID_20260217_113534_00_425_2026-03-26_14-14-25_screenshot"
    },
    {
      "id": "panorama_6992C73E_7C4C_C3FA_41BD_59619C4CA785",
      "label": "VID_20260217_113702_00_426_2026-03-26_14-14-48_screenshot"
    },
    {
      "id": "panorama_6F5905C9_7C4C_4686_41AD_75765084A0FB",
      "label": "VID_20260217_113702_00_426_2026-03-26_14-15-15_screenshot"
    },
    {
      "id": "panorama_6F59FCD8_7C4C_4686_41B2_C265078ADAA7",
      "label": "VID_20260217_113823_00_427_2026-03-26_14-18-04_screenshot"
    },
    {
      "id": "panorama_6F5913E2_7C4C_428A_41C0_5AD96767B167",
      "label": "VID_20260217_113902_00_428_2026-03-26_14-18-53_screenshot"
    },
    {
      "id": "panorama_6F59CB18_7C4C_4386_41BB_D57C9370F526",
      "label": "VID_20260217_113932_00_429_2026-03-26_14-19-34_screenshot"
    },
    {
      "id": "panorama_6F59F27A_7C4C_427A_41D0_44DDEFCC0BC1",
      "label": "VID_20260217_113948_00_430_2026-03-26_14-20-18_screenshot"
    },
    {
      "id": "panorama_6F5A89E3_7C4C_CE8A_41D5_C47ED4591027",
      "label": "VID_20260217_114016_00_431_2026-03-26_14-20-59_screenshot"
    },
    {
      "id": "panorama_6F5960EC_7C4C_DE9D_41D1_E00E6F2F74FC",
      "label": "VID_20260217_114016_00_431_2026-03-26_14-21-13_screenshot"
    },
    {
      "id": "panorama_6F596864_7C4C_CD8E_41BB_4AD5C09CF432",
      "label": "VID_20260217_114224_00_432_2026-03-26_14-21-52_screenshot"
    },
    {
      "id": "panorama_6F594052_7C4C_FD8A_41DE_EBCF8977D568",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-24_screenshot"
    },
    {
      "id": "panorama_6F5AB7CA_7C4C_C29A_41D8_B732BD5E56B3",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-36_screenshot"
    },
    {
      "id": "panorama_6F595EB7_7C4C_C28A_4188_BA3415271B80",
      "label": "VID_20260217_114336_00_433_2026-03-26_14-22-46_screenshot"
    },
    {
      "id": "panorama_6F5AA626_7C4C_C58A_41D3_2319D74A1D3A",
      "label": "VID_20260217_114443_00_434_2026-03-26_14-23-15_screenshot"
    },
    {
      "id": "panorama_6F5ACD8E_7C4C_469A_41D7_F15459ACDAD3",
      "label": "VID_20260217_114443_00_434_2026-03-26_14-23-39_screenshot"
    }
  ],
  "Muzdalifah": [
    {
      "id": "panorama_818474DF_8B44_BA01_41D9_8F1D94AB5DAE",
      "label": "VID_20260217_123132_00_485_2026-03-26_14-48-41_screenshot"
    },
    {
      "id": "panorama_818479F6_8B44_CA03_41CC_7C01EAD97DA5",
      "label": "VID_20260217_124447_00_486_2026-03-26_14-49-11_screenshot"
    },
    {
      "id": "panorama_81840E5A_8B44_C603_41CB_DD32C22DD4A9",
      "label": "VID_20260217_124447_00_486_2026-03-26_14-49-41_screenshot"
    },
    {
      "id": "panorama_818412B2_8B44_FE03_41D3_A97F25DF4CCB",
      "label": "VID_20260217_124606_00_487_2026-03-26_14-53-46_screenshot"
    },
    {
      "id": "panorama_8184E797_8B44_C601_41D9_A488ED02B92B",
      "label": "VID_20260217_124721_00_488_2026-03-26_14-54-25_screenshot"
    },
    {
      "id": "panorama_81843C87_8B44_CA02_41C8_C5C950642155",
      "label": "VID_20260217_124823_00_489_2026-03-26_14-54-47_screenshot"
    },
    {
      "id": "panorama_8184E14B_8B44_BA01_41DD_609207BB3DF0",
      "label": "VID_20260217_124823_00_489_2026-03-26_14-55-00_screenshot"
    },
    {
      "id": "panorama_81841664_8B44_4606_41CC_401DE865B161",
      "label": "VID_20260217_124931_00_490_2026-03-26_14-55-21_screenshot"
    },
    {
      "id": "panorama_8181AB7D_8B44_4E01_41D9_F0C622DD8FEE",
      "label": "VID_20260217_124931_00_490_2026-03-26_14-56-08_screenshot"
    },
    {
      "id": "panorama_871E8FB1_8B44_4601_4196_4F4B28434C5D",
      "label": "VID_20260217_125139_00_491_2026-03-26_14-56-37_screenshot"
    }
  ]
};
  var SCENE_KEY_TO_FOLDER = {
  "tawaf-initial": "1 Tawaf",
  "tawaf-ifadha": "1 Tawaf",
  "tawaf-farewell": "1 Tawaf",
  "safa-marwa": "2 Safa and Marwa",
  "mina-8th": "3 Mina",
  "mina-tents-12": "3 Mina",
  "arafah-9th": "4 Arafah",
  "muzdalifah-9th": "Muzdalifah",
  "jamarat-10th": "Jamarat Aqabah",
  "jamarat-11th": "Jamarat Base 2",
  "jamarat-12th": "Jamarat Base 2",
  "barber-umrah": null,
  "rest-umrah": null,
  "reenter-ihram": null,
  "qurbani-10th": null,
  "barber-hajj": null
};
  window.PPPanoramaCatalog = {
    forFolder: function(folder){ return (BY_FOLDER[folder]||[]).slice(); },
    forSceneKey: function(key){
      var f = SCENE_KEY_TO_FOLDER[key];
      return f ? (BY_FOLDER[f]||[]).slice() : [];
    },
    folderForSceneKey: function(key){ return SCENE_KEY_TO_FOLDER[key] || null; },
    label: function(folder, id){
      var p = (BY_FOLDER[folder]||[]).find(function(x){return x.id===id;});
      return p ? p.label : "";
    },
    folders: function(){ return Object.keys(BY_FOLDER); }
  };
})();
